version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kreativroni-api"
s3_bucket = "kreativroni-api"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
