AWSTemplateFormatVersion: "2010-09-09"
Description: "kreativroni API."
Transform: "AWS::Serverless-2016-10-31"


Parameters:
  VaultToken:
    Type: "String"

AWSTemplateFormatVersion: "2010-09-09"
Description: "kreativroni API project."
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  VaultToken:
    Type: "String"
    Default: "default"
  APIKEY:
    Type: "String"
  APPKEY:
    Type: "String"
  ProductsKEY:
    Type: "String"


Resources:

  products:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
      BuildMethod: go1.x 
    Properties:
      CodeUri: .
      Handler: products
      FunctionName: !Sub "products"
      Timeout: 10
      Runtime: "provided.al2"
      Architecture:
        - x86_64
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        ApiEvent:
          Type: "HttpApi"
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/products"
            Method: "get"

  productsImport:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: productsImport
      FunctionName: !Sub "productsImport"
      Timeout: 10
      Runtime: "provided.al2"
      Architecture:
        - x86_64
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/import"
            Method: "get"

  sections:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
      BuildMethod: go1.x 
    Properties:
      CodeUri: .
      Handler: sections
      FunctionName: !Sub "sections"
      Timeout: 10
      Runtime: "provided.al2"
      Architecture:
        - x86_64
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/sections"
            Method: "get"

  productVariations:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
      BuildMethod: go1.x 
    Properties:
      CodeUri: .
      Handler: productVariations
      FunctionName: !Sub "productVariations"
      Timeout: 10
      Runtime: "provided.al2"
      Architecture:
        - x86_64
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/variations"
            Method: "get"

  news:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
      BuildMethod: go1.x 
    Properties:
      CodeUri: .
      Handler: sections
      FunctionName: !Sub "news"
      Timeout: 10
      Runtime: "provided.al2"
      Architecture:
        - x86_64
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/news"
            Method: "get"
        ApiParam:
          Type: "Api"
          Properties:
            Path: "/api/v1/news/{id}"
            Method: "get"

  newsPut:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
      BuildMethod: go1.x 
    Properties:
      CodeUri: .
      Handler: newsPut
      FunctionName: !Sub "newsPut"
      Timeout: 10
      Runtime: "provided.al2"
      Architecture:
        - x86_64
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/news"
            Method: "put"

  newsDelete:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
      BuildMethod: go1.x 
    Properties:
      CodeUri: .
      Handler: newsDelete
      FunctionName: !Sub "newsDelete"
      Timeout: 10
      Runtime: "provided.al2"
      Architecture:
        - x86_64
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/news/{id}"
            Method: "delete"

  orders:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
      BuildMethod: go1.x 
    Properties:
      CodeUri: .
      Handler: orders
      FunctionName: !Sub "orders"
      Timeout: 10
      Runtime: "provided.al2"
      Architecture:
        - x86_64
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/orders"
            Method: "get"
        ApiParam:
          Type: "Api"
          Properties:
            Path: "/api/v1/orders/{id}"
            Method: "get"

  ordersPut:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
      BuildMethod: go1.x 
    Properties:
      CodeUri: .
      Handler: ordersPut
      FunctionName: !Sub "ordersPut"
      Timeout: 10
      Runtime: "provided.al2"
      Architecture:
        - x86_64
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/orders"
            Method: "put"

  customers:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
      BuildMethod: go1.x 
    Properties:
      CodeUri: .
      Handler: customers
      FunctionName: !Sub "customers"
      Timeout: 10
      Runtime: "provided.al2"
      Architecture:
        - x86_64
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/customers"
            Method: "get"
        ApiParam:
          Type: "Api"
          Properties:
            Path: "/api/v1/customers/{id}"
            Method: "get"

  customersPut:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
      BuildMethod: go1.x 
    Properties:
      CodeUri: .
      Handler: customersPut
      FunctionName: !Sub "customersPut"
      Timeout: 10
      Runtime: "provided.al2"
      Architecture:
        - x86_64
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/customers"
            Method: "put"

  customersDelete:
    Type: "AWS::Serverless::Function"
    Metadata:
      BuildMethod: makefile
      BuildMethod: go1.x 
    Properties:
      CodeUri: .
      Handler: customersDelete
      FunctionName: !Sub "customersDelete"
      Timeout: 10
      Runtime: "provided.al2"
      Architecture:
        - x86_64
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/customers/{id}"
            Method: "delete"
