AWSTemplateFormatVersion: "2010-09-09"
Description: "kreativroni API."
Transform: "AWS::Serverless-2016-10-31"


Parameters:
  VaultToken:
    Type: "String"

AWSTemplateFormatVersion: "2010-09-09"
Description: "kreativroni API project."
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  VaultToken:
    Type: "String"
    Default: "default"
  APIKEY:
    Type: "String"
  APPKEY:
    Type: "String"
  ProductsKEY:
    Type: "String"

Globals:
  Function:
    Handler: "main"
    Timeout: 10
    Runtime: "go1.x"


Resources:

  products:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: "cmd/products"
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        ApiEvent:
          Type: "HttpApi"
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/products"
            Method: "get"

  products-import:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: "cmd/products-import"
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        ApiEvent:
          Type: "HttpApi"
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/import"
            Method: "get"

  sections:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: "cmd/sections"
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/sections"
            Method: "get"

  productVariations:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: "cmd/product-variations"
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/variations"
            Method: "get"

  news:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: "cmd/news"
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/news"
            Method: "get"
        ApiParam:
          Type: "Api"
          Properties:
            Path: "/api/v1/news/{id}"
            Method: "get"

  newsPut:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: "cmd/newsPut"
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/news"
            Method: "put"

  newsDelete:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: "cmd/newsDelete"
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/news/{id}"
            Method: "delete"

  orders:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: "cmd/orders"
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/orders"
            Method: "get"
        ApiParam:
          Type: "Api"
          Properties:
            Path: "/api/v1/orders/{id}"
            Method: "get"

  ordersPut:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: "cmd/ordersPut"
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/orders"
            Method: "put"

  customers:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: "cmd/customers"
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/customers"
            Method: "get"
        ApiParam:
          Type: "Api"
          Properties:
            Path: "/api/v1/customers/{id}"
            Method: "get"

  customersPut:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: "cmd/customersPut"
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/customers"
            Method: "put"

  customersDelete:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: "cmd/customersDelete"
      Environment:
        Variables:
          API_KEY: !Ref APIKEY
          APP_KEY: !Ref APPKEY
          PRODUCTS_KEY: !Ref ProductsKEY
      Events:
        Api:
          Type: "Api"
          Properties:
            Path: "/api/v1/customers/{id}"
            Method: "delete"