name: kreativroni API deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      # Build using SAM
      - run: sam build
      # Deploy on AWS
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-file samconfig.toml
