name: kreativroni API deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      # Build using SAM
      - run: export PRODUCTS_KEY=${{ secrets.PRODUCTS_KEY }} && export APP_KEY=${{ secrets.APP_KEY }} && export API_KEY=${{ secrets.API_KEY }} && sam build -t template.yml
      # Deploy on AWS
      - run: export PRODUCTS_KEY=${{ secrets.PRODUCTS_KEY }} && export APP_KEY=${{ secrets.APP_KEY }} && export API_KEY=${{ secrets.API_KEY }} && sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name kreativroni-api --s3-bucket kreativroni-api --capabilities CAPABILITY_IAM --region eu-central-1 -t template.yml