name: kreativroni API deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      # Build using SAM
      - run: sam build --use-container --template-file template.yml
        with:
          PRODUCTS_KEY: ${{ secrets.PRODUCTS_KEY }}
          APP_KEY: ${{ secrets.APP_KEY }}
          API_KEY: ${{ secrets.API_KEY }}
      # Deploy on AWS
      - run: sam deploy -t template.yml
        with:
          PRODUCTS_KEY: ${{ secrets.PRODUCTS_KEY }}
          APP_KEY: ${{ secrets.APP_KEY }}
          API_KEY: ${{ secrets.API_KEY }}